version: '3.9'
services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: >
      sh -c "
        rm -rf tmp/pids/server.pid \
        & bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/mini-seedrs-api
    ports:
      - 3000:3000
    depends_on:
      - postgres
    tty: true
    stdin_open: true
volumes:
  postgres-data: